services:
  - type: web
    plan: free
    name: enterprise-ai-document-assistant-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MODEL_PROVIDER
        value: groq
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "120"
      - key: DATABASE_URL
        value: sqlite+aiosqlite:///vector_store/chat_history.db
      - key: REDIS_URL
        sync: false
